taxa = ["acipenseridae_acipenser_medirostris","catostomidae_catostomus_luxatus","acipenseridae_acipenser_medirostris","acipenseridae_acipenser_transmontanus","acipenseridae_acipenser_medirostris","acipenseridae_acipenser_medirostris","acipenseridae_acipenser_transmontanus","catostomidae_catostomus_snyderi","acipenseridae_acipenser_transmontanus","catostomidae_catostomus_occidentalis","acipenseridae_acipenser_transmontanus","catostomidae_catostomus_luxatus","catostomidae_catostomus_occidentalis","catostomidae_chasmistes_brevirostris","catostomidae_catostomus_occidentalis","cottidae_cottus_gulosus","catostomidae_catostomus_occidentalis","catostomidae_catostomus_snyderi","cyprinidae_hesperoleucus_venustus","cottidae_cottus_klamathensis","cottidae_cottus_gulosus","cyprinidae_lavinia_exilicauda","cottidae_cottus_gulosus","catostomidae_chasmistes_brevirostris","cyprinidae_lavinia_exilicauda","cyprinidae_gila_coerulea","cottidae_cottus_klamathensis","cyprinidae_mylopharodon_conocephalus","cyprinidae_hesperoleucus_venustus","gasterosteidae_gasterosteus_aculeatus","cyprinidae_mylopharodon_conocephalus","NA","cyprinidae_ptychocheilus_grandis","cyprinidae_ptychocheilus_grandis","cyprinidae_lavinia_exilicauda","petromyzontidae_entosphenus_similis","cyprinidae_pogonichthys_macrolepidotus","NA","gasterosteidae_gasterosteus_aculeatus","gasterosteidae_gasterosteus_aculeatus","cyprinidae_mylopharodon_conocephalus","petromyzontidae_entosphenus_tridentata","cyprinidae_ptychocheilus_grandis","NA","gobiidae_eucyclogobius_newberryi","osmeridae_spirinchus_thaleichthys","cyprinidae_pogonichthys_macrolepidotus","salmonidae_oncorhynchus_kisutch","embiotocidae_hysterocarpus_traskii","NA","osmeridae_spirinchus_thaleichthys","petromyzontidae_entosphenus_tridentata","cyprinidae_ptychocheilus_grandis","salmonidae_oncorhynchus_mykiss","gasterosteidae_gasterosteus_aculeatus","NA","petromyzontidae_entosphenus_similis","petromyzontidae_lampetra_ayersi","embiotocidae_hysterocarpus_traskii","salmonidae_oncorhynchus_tshawytscha","osmeridae_hypomesus_pacificus","NA","petromyzontidae_entosphenus_tridentata","petromyzontidae_lampetra_richardsoni","gasterosteidae_gasterosteus_aculeatus","NA","petromyzontidae_entosphenus_tridentata","NA","petromyzontidae_lampetra_ayersi","salmonidae_oncorhynchus_kisutch","gobiidae_eucyclogobius_newberryi","NA","petromyzontidae_lampetra_ayersi","NA","petromyzontidae_lampetra_richardsoni","salmonidae_oncorhynchus_mykiss","petromyzontidae_entosphenus_tridentata","NA","petromyzontidae_lampetra_richardsoni","NA","salmonidae_oncorhynchus_kisutch","salmonidae_oncorhynchus_tshawytscha","petromyzontidae_lampetra_ayersi","NA","salmonidae_oncorhynchus_mykiss","NA","salmonidae_oncorhynchus_mykiss","NA","petromyzontidae_lampetra_richardsoni","NA","NA","NA","salmonidae_oncorhynchus_tshawytscha","NA","salmonidae_oncorhynchus_kisutch","NA","NA","NA","NA","NA","salmonidae_oncorhynchus_mykiss","NA","NA","NA","NA","NA","salmonidae_oncorhynchus_tshawytscha"]

taxa = [taxon.replace("_"," ") for taxon in taxa]

taxa_set = list(set(taxa))

for taxon in sorted(taxa_set):
	print(taxon)
	

print(len(taxa_set))