taxa = ["Pacific_lamprey","Pacific_lamprey","Pacific_lamprey","Pacific_lamprey","Pacific_lamprey","River_lamprey","River_lamprey","River_lamprey","Klamath_River_lamprey","Klamath_River_lamprey","Western_brook_lamprey","Western_brook_lamprey","Western_brook_lamprey","River_lamprey","River_lamprey","Southern_green_sturgeon","Northern_green_sturgeon","Southern_green_sturgeon","Western_brook_lamprey","Western_brook_lamprey","White_sturgeon","White_sturgeon","White_sturgeon","Northern_green_sturgeon","Northern_green_sturgeon","Sacramento_hitch","Sacramento_hitch","Sacramento_hitch","White_sturgeon","White_sturgeon","Sacramento_splittail","Hardhead","California_roach","Longfin_smelt","Blue_chub","Longfin_smelt","Sacramento_pikeminnow","Southern_coastal_roach","Upper_Klamath_Trinity_fall_Chinook_salmon","Klamath_largescale_sucker","Delta_smelt","Sacramento_sucker","Sacramento_splittail","Upper_Klamath_Trinity_spring_Chinook_salmon","Lost_River_sucker","Central_Valley_winter_Chinook_salmon","Longfin_smelt","Hardhead","Southern_Oregon_Northern_California_coast_coho_salmon","Shortnose_sucker","Central_Valley_spring_Chinook_salmon","California_Coast_fall_Chinook_salmon","Sacramento_pikeminnow","Klamath_Mountains_Province_winter_steelhead","Upper_Klamath_Trinity_fall_Chinook_salmon","Central_Valley_late_fall_Chinook_salmon","Central_Coast_coho_salmon","Sacramento_sucker","Klamath_Mountains_Province_summer_steelhead","Upper_Klamath_Trinity_spring_Chinook_salmon","Central_Valley_fall_Chinook_salmon","Southern_Oregon_Northern_California_coast_coho_salmon","Longfin_smelt","Lower_Klamath_marbled_sculpin","Southern_Oregon_Northern_California_coast_coho_salmon","Central_California_coast_winter_steelhead","Northern_California_coast_winter_steelhead","Delta_smelt","Inland_threespine_stickleback","Klamath_Mountains_Province_winter_steelhead","Inland_threespine_stickleback","Northern_California_coast_summer_steelhead","California_Coast_fall_Chinook_salmon","Tidewater_goby","Klamath_Mountains_Province_summer_steelhead","Sacramento_tule_perch","Inland_threespine_stickleback","Central_Valley_spring_Chinook_salmon","Upper_Klamath_marbled_sculpin","Tidewater_goby","Central_Coast_coho_salmon","Inland_threespine_stickleback","Central_California_coast_winter_steelhead","Tidewater_goby","Riffle_sculpin","Inland_threespine_stickleback","Sacramento_tule_perch","Tidewater_goby",]

taxa = [taxon.replace("_"," ") for taxon in taxa]

taxa_set = list(set(taxa))

for taxon in sorted(taxa_set):
	print(taxon)
	

print(len(taxa_set))