---
title: "species_table"
author: "Nick Santos"
date: "June 13, 2018"
output: 
  html_document:
    df_print: paged
    css: mystyle.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r species_listing, echo=FALSE}

writeLines("td, th { padding : 6px } th { background-color : #fff ; color : #000; border : 1px solid #333; } td { color : #000 ; border : 1px solid #333 }", con = "mystyle.css")  # add the CSS for the data tables

sci_names <- c("Entosphenus tridentata",
"Entosphenus similis",
"Lampetra ayersi",
"Lampetra hubbsi",
"Lampetra richardsoni",
"Acipenser medirostris",
"Acipenser medirostris",
"Acipenser transmontanus",
"Siphatales bicolor snyderi",
"Gila coerulea",
"Gila orcutti",
"Lavinia exilicauda exilicauda",
"Lavinia exilicauda harengeus",
"Hesperoleucus symmetricus symmetricus",
"Hesperoleucus symmetricus subspecies",
"Hesperoleucus symmetricus subditus",
"Hesperoleucus symmetricus subspecies",
"Hesperoleucus mitrulus",
"Pogonichthys macrolepidotus",
"Mylopharodon conocephalus",
"Ptychocheilus grandis",
"Rhinichthys osculus subspecies",
"Rhinichthys osculus robustus",
"Rhinichthys osculus subspecies",
"Rhinichthys osculus subspecies",
"Pantosteus lahontan",
"Catostomus occidentalis occidentalis",
"Catostomus occidentalis mnioltiltus",
"Catostomus microps",
"Catostomus snyderi",
"Catostomus luxatus",
"Catostomus santaanae",
"Chasmistes brevirostris",
"Xyrauchen texanus",
"Spirinchus thaleichthys",
"Hypomesus pacificus",
"Prosopium williamsoni",
"Oncorhynchus tshawytscha",
"Oncorhynchus tshawytscha",
"Oncorhynchus tshawytscha",
"Oncorhynchus tshawytscha",
"Oncorhynchus tshawytscha",
"Oncorhynchus tshawytscha",
"Oncorhynchus tshawytscha",
"Oncorhynchus kisutch",
"Oncorhynchus kisutch",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss",
"Oncorhynchus mykiss gilberti",
"Oncorhynchus clarki henshawi",
"Cyprinodon macularius",
"Cyprinodon radiosus",
"Cottus klamathensis macrops",
"Cottus klamathensis polyporus",
"Cottus klamathensis klamathensis",
"Cottus gulosus",
"Cottus pitensis",
"Gasterosteus aculeatus microcephalus",
"Gasterosteus aculeatus williamsoni",
"Archoplites interruptus",
"Hysterocarpus traskii traskii",
"Eucyclogobius newberryi",
"Hesperoleucus symmetricus")

common_names <- c("Pacific lamprey",
"Klamath River lamprey",
"River lamprey",
"Kern brook lamprey",
"Western brook lamprey",
"Northern green sturgeon",
"Southern green sturgeon",
"White sturgeon",
"Owens tui chub",
"Blue chub",
"Arroyo chub",
"Sacramento hitch",
"Monterey hitch",
"California roach",
"Red Hills roach",
"Southern coastal roach",
"Tomales roach",
"Northern roach",
"Sacramento splittail",
"Hardhead",
"Sacramento pikeminnow",
"Sacramento speckled dace",
"Lahontan speckled dace",
"Owens speckled dace",
"Santa Ana speckled dace",
"Lahontan mountain sucker",
"Sacramento sucker",
"Monterey sucker",
"Modoc sucker",
"Klamath largescale sucker",
"Lost River sucker",
"Santa Ana sucker",
"Shortnose sucker",
"Razorback sucker",
"Longfin smelt",
"Delta smelt",
"Mountain whitefish",
"Upper Klamath-Trinity fall Chinook salmon",
"Upper Klamath-Trinity spring Chinook salmon",
"California Coast fall Chinook salmon",
"Central Valley winter Chinook salmon",
"Central Valley spring Chinook salmon",
"Central Valley late fall Chinook salmon",
"Central Valley fall Chinook salmon",
"Central Coast coho salmon",
"Southern Oregon Northern California coast coho salmon",
"Northern California coast winter steelhead",
"Northern California coast summer steelhead",
"Klamath Mountains Province winter steelhead",
"Klamath Mountains Province summer steelhead",
"Central California coast winter steelhead",
"South Central California coast steelhead",
"Southern California steelhead",
"Kern River rainbow trout",
"Lahontan cutthroat trout",
"Desert pupfish",
"Owens pupfish",
"Bigeye marbled sculpin",
"Lower Klamath marbled sculpin",
"Upper Klamath marbled sculpin",
"Riffle sculpin",
"Pit sculpin",
"Inland threespine stickleback",
"Unarmored threespine stickleback",
"Sacramento perch",
"Sacramento tule perch",
"Tidewater goby",
"Kaweah roach")

flow_sensitive_species <- cbind(sci_names, common_names)
colnames(flow_sensitive_species) <- c("Scientific_Name", "Common_Name")
show(knitr::kable(flow_sensitive_species, format="html"))
  
  
```
